# Generated by Django 4.1.1 on 2022-10-02 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('move', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='家具')),
                ('width', models.IntegerField(verbose_name='横幅')),
                ('height', models.IntegerField(verbose_name='縦幅')),
                ('image_path', models.URLField(verbose_name='画像ファイル')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '家具',
                'verbose_name_plural': '家具',
            },
        ),
        migrations.AlterField(
            model_name='arrangement',
            name='furniture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='move.furniture'),
        ),
    ]
